### ISSUE TITLE
Is it possible to disable selected date range?

### ISSUE THREAD

**Issue by Govindbetterlives** [funyin/date_ranger#4]
Hi, How to disable the selected date range?

**Comment by funyin** [comment]
Do you mean to prevent the user from selecting a particular date range?

**Comment by Govindbetterlives** [comment]
Yes, exactly.

**Comment by funyin** [comment]
Yeah, you can. You are responsible for updating the UI when the user selects a date, so you can decide not to update the ui for different changes.

```dart
DateRanger(
          initialRange: initialDateRange,
          onRangeChanged: (range) {
            setState(() {
              initialDateRange = range;
            });
          },
        )
