### ISSUE TITLE
Year & month scroll issues.

### ISSUE THREAD

**Issue by Govindbetterlives** [funyin/date_ranger#5]
Hi, When I scroll the year or month widget, it will scroll even the year.
The problem comes only on the web platform.
Ex:
Attached image. In this image, it shows the year 2022. When I scroll it skips 2023 and shows 2024.

In Month, It shows April. When I scroll it skips May and shows June.

![image](https://user-images.githubusercontent.com/81243940/195836554-1a1e8a13-f7ab-4528-b14c-f0d0cb0a50d8.png)

**Comment by funyin** [comment]
Thanks for raising this issue @Govindbetterlives I'll look into it and get back to you shortly

**Comment by Govindbetterlives** [comment]
This issue is still active. Any updates regarding that?

**Comment by funyin** [comment]
Confirmed that this is not occurring on flutter 3.0.0. 
Resolved with [1.0.0](https://github.com/funyin/date_ranger/tree/release/1.0.0)
