### ISSUE TITLE
Is possible to show weekdays title in this widget?

### ISSUE THREAD

**Issue by Govindbetterlives** [funyin/date_ranger#6]
How to view weekdays title.

Ex: 
![image](https://user-images.githubusercontent.com/81243940/200296484-86811025-e83a-4cb8-874c-e157026507bd.png)

**Comment by funyin** [comment]
Yes it is possible

**Comment by Govindbetterlives** [comment]
Can you guide me pls.

**Comment by funyin** [comment]
Oh sorry I meant, I'll have to add that to the new version. I am currently working on an update this week. I can add that and let you know once it is ready

**Comment by funyin** [comment]
Resolved with [1.0.0](https://github.com/funyin/date_ranger/tree/release/1.0.0)
